### PR TITLE
Deprecate help-link plugin

### PR DESCRIPTION
**Pull request by oliverguenther**

### CODE REVIEW

**Comment by machisuji** [comment]
Shouldn't we just delete the repo?

**Comment by machisuji** [comment]
nvm saw the deprecation warning

**Comment by machisuji** [comment]
@oliverguenther The plugin is not entirely obsolete, is it? I mean it allows changing the link at runtime via the settings. The core only supports it via configuration.

**Comment by oliverguenther** [comment]
Yes, but changing it dynamically makes no sense IMHO and the help link breaks with functionality of 5.1. Since we have no use for it, a user wanting to fix dynamic setting of the link can still fork the plugin.

**Comment by machisuji** [comment]
Alright.

**Pull request merged**
